# Generated by Django 4.1 on 2022-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
